import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadProject } from "./config.js";
import { GENERATED_DIR, type CrossPlatformTarget } from "./types.js";

function toPascalCase(name: string): string {
  return name
    .split(/[_\s-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function renderTypes(targets: CrossPlatformTarget[]): string {
  const caps = [...new Set(targets.flatMap((t) => t.capabilities))].sort();
  const capUnion = caps.length
    ? caps.map((c) => JSON.stringify(c)).join(" | ")
    : "never";
  const targetUnion = targets.map((t) => JSON.stringify(t.id)).join(" | ");

  return `/* eslint-disable */
// Generated by @client-platform/cross-platform — do not edit by hand.

export type TargetId = ${targetUnion || "never"};
export type Capability = ${capUnion};

export type TargetSupport = "supported" | "experimental";

export type TargetDescriptor = {
  id: TargetId;
  capabilities: readonly Capability[];
  support: TargetSupport;
};
`;
}

function renderConstants(targets: CrossPlatformTarget[]): string {
  const lines = targets
    .map((t) => {
      const caps = t.capabilities.map((c) => JSON.stringify(c)).join(", ");
      return `  {\n    id: ${JSON.stringify(t.id)},\n    capabilities: [${caps}] as const,\n    support: ${JSON.stringify(t.support)},\n  },`;
    })
    .join("\n");

  return `/* eslint-disable */
// Generated by @client-platform/cross-platform — do not edit by hand.
import type { TargetDescriptor } from "./types.js";

export const TARGETS = [
${lines}
] as const satisfies readonly TargetDescriptor[];
`;
}

function renderSeam(target: CrossPlatformTarget): string {
  const name = toPascalCase(target.id);
  const caps = target.capabilities.map((c) => JSON.stringify(c)).join(" | ");
  return `/* eslint-disable */
// Generated by @client-platform/cross-platform — do not edit by hand.
import type { Capability } from "../types.js";

export const targetId = ${JSON.stringify(target.id)} as const;
export const support = ${JSON.stringify(target.support)} as const;
export type ${name}Capability = ${caps || "never"};

/** Seam stub — wire real adapters in a later milestone. */
export function create${name}Seam(): {
  id: typeof targetId;
  has(capability: Capability): boolean;
} {
  const capabilities = new Set<Capability>([${target.capabilities
    .map((c) => JSON.stringify(c))
    .join(", ")}]);
  return {
    id: targetId,
    has(capability) {
      return capabilities.has(capability);
    },
  };
}
`;
}

function renderIndex(targets: CrossPlatformTarget[]): string {
  const exports = targets
    .map((t) => `export * as ${t.id.replace(/-/g, "_")} from "./seams/${t.id}.js";`)
    .join("\n");
  return `/* eslint-disable */
// Generated by @client-platform/cross-platform — do not edit by hand.
export * from "./types.js";
export * from "./constants.js";
${exports}
`;
}

export async function runGenerate(cwd: string): Promise<string[]> {
  const project = await loadProject(cwd);
  if (!project.product) {
    throw new Error("products.crossPlatform missing or invalid; run cross-platform init");
  }

  const outDir = path.join(cwd, GENERATED_DIR);
  const seamsDir = path.join(outDir, "seams");
  await mkdir(seamsDir, { recursive: true });

  const files: Array<[string, string]> = [
    ["types.ts", renderTypes(project.product.targets)],
    ["constants.ts", renderConstants(project.product.targets)],
    ["index.ts", renderIndex(project.product.targets)],
  ];
  for (const target of project.product.targets) {
    files.push([`seams/${target.id}.ts`, renderSeam(target)]);
  }

  const written: string[] = [];
  for (const [name, contents] of files) {
    const filePath = path.join(outDir, name);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, contents, "utf8");
    written.push(path.relative(cwd, filePath));
  }
  return written;
}
