import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  defaultProductConfig,
  writeProjectManifest,
  writeWorkspaceConfig,
} from "./config.js";
import { pathExists } from "./fs-utils.js";
import {
  DEFAULT_PRESET,
  DEFAULT_SHARED_CORE,
} from "./types.js";

export async function runInit(cwd: string, preset: string): Promise<string[]> {
  if (preset !== DEFAULT_PRESET) {
    throw new Error(`unsupported preset: ${preset} (supported: ${DEFAULT_PRESET})`);
  }

  const written: string[] = [];
  const product = defaultProductConfig(preset);

  const configPath = await writeWorkspaceConfig(cwd, product);
  written.push(path.relative(cwd, configPath) || path.basename(configPath));

  const manifestPath = await writeProjectManifest(cwd, {
    targets: product.targets.map((t) => t.id),
    tooling: ["vite"],
  });
  written.push(path.relative(cwd, manifestPath) || path.basename(manifestPath));

  const sharedCore = path.join(cwd, DEFAULT_SHARED_CORE);
  if (!(await pathExists(sharedCore))) {
    await mkdir(sharedCore, { recursive: true });
    const indexFile = path.join(sharedCore, "index.ts");
    await writeFile(
      indexFile,
      `// Shared core stub generated by @client-platform/cross-platform\nexport const sharedCoreVersion = "0.0.0";\n`,
      "utf8",
    );
    written.push(path.relative(cwd, indexFile));
  }

  return written;
}
